name: Docker Image CI

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.16.0-alpine]

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker compose up -d
    
    - name: Mocha
      run: npm install mocha
    
    - name: NPM Test
      run: npm test

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.PAT }}
        commit-message: Automated PR
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: main
        title: 'Automated PR'
        body: |
          Update report
          - Updated with *today's* date
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        labels: |
          report
          automated pr
        team-reviewers: |
          owners
          maintainers
        milestone: 1
        draft: false
